# Generated by Django 4.0.3 on 2022-03-29 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('is_prioritized', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('1', 'submitted'), ('2', 'in progress'), ('3', 'completed')], default='1', max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_prioritized', 'created'],
            },
        ),
    ]
